logging:
  level:
    org:
      springframework:
        security: DEBUG

userDatabase:
  host: postgres.yatripulse.internal/user_service_stage
  username: postgres
  password: 8t=J76x@*A
  awsRegion: ap-south-1
        
aws:
  accessKey: AKIA47CRYRRYFV47GJPD
  secretKey: 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

server:
  port: 80