database:
  # host: 172.16.5.55/abha_service_prod
  host: 192.168.1.161/postgres
  username: postgres
  password: postgres

userDatabase:
  # host: 172.16.5.55/user_service_prod
  host: 192.168.1.161/postgres
  username: postgres
  password: postgres

spring:
  data:
  

     redis:
      host: "192.168.1.161"
      password: "cxdyZT0e2RmYK9B7uq45UyKs3H5teyUH"
      port: 6379
      timeout: 300

logging:
  level:
    org:
      springframework:
        security: DEBUG

aws:
  accessKey: AKIA47CRXQFJDZGI6WES
  secretKey: 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
server:
  port: 9004

baseUrl:
  userService: "http://127.0.0.1:9001"
  notificationService: "http://127.0.0.1:9002"
  healthService: "http://127.0.0.1:9003"
  abhaService: "http://127.0.0.1:9004"
