{{- range $app_key,$app_value := .Values.apps}}

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $app_key}}"
  labels:
    app.kubernetes.io/name: {{$app_key}}
    release: {{$.Release.Name}}
spec:
  ports:
    - port: {{$.Values.service.port}}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{$app_key}}
    release: {{$.Release.Name}}
---
  {{- end}}
