server:
  port: 80

Spring:
  exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  profiles:
    active: "dev"
logging:
  level:
    root: INFO
    org.wishfoundation.healthservice: DEBUG