#database:
#  globalDataSource:
#    host: ap-south-1-tenants-1.cbxgfplzpwhh.ap-south-1.rds.amazonaws.com/char_dham
#    username: postgres
#    password: W7K0TdPuOXuTTuzmSzGJ
#    awsRegion: ap-southeast-1       
# 
aws:
  accessKey: AKIA47CRXQFJDZGI6WES
  secretKey: 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

userDatabase:
  host: 13.201.203.168/user_service_dev
  username: postgres
  password: Wish1234@
  awsRegion: ap-south-1

database:
  host: 13.201.203.168/health_service_dev
  username: postgres
  password: Wish1234@
  awsRegion: ap-south-1

spring:
  data:
    redis:
      host: "13.201.203.168"
      password: "Wish1234@"
      port: 6379
      timeout: 300


server:
  port: 8082

baseUrl:
  userService: "http://localhost:8080"
  notificationService: "http://localhost:8081"
  healthService: "http://localhost:8082"
  abhaService: "http://localhost:8083"