apps:
  user-service:
    image: user-service
    replicaCount: '1'
    minPodCount : '1'
    maxPodCount : '1'
    podMinRam : 2000Mi
    cpuRequest : '.2'
    podMaxRam: 3000Mi
    cpuLimit: '1'
    apiPath:
      - /user-service