database:
  host: ap-south-1-tenants-1.cbxgfplzpwhh.ap-south-1.rds.amazonaws.com/iam_dev
  username: postgres
  password: W7K0TdPuOXuTTuzmSzGJ
  awsRegion: ap-south-1

spring:
  data:
    redis:
      host: "35.240.168.13"
      password: "fPz6RMnCAgWg"
      port: 6379
      timeout: 300

logging:
  level:
    org:
      springframework:
        security: DEBUG
        
aws:
  accessKey: AKIA47CRXQFJDZGI6WES
  secretKey: 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
server:
  port: 80

baseUrl:
  userService: "http://localhost:8080"
  notificationService: "http://localhost:8081"
  healthService: "http://localhost:8082"
  abhaService: "http://localhost:8083"
